### ISSUE TITLE
Grid becomes balnk for certain resolution on scroll

### ISSUE THREAD

**Issue by manishasn161** [rwilson504/PCFControls#116]
I observed that with certain resolutions, on scroll grid turns blank. I have to make use of Refresh button to make data in grid to appear again. Is it a know issue and any fix available for it?

**Comment by rwilson504** [comment]
A few questions
* Is this within Canvas or Model App?
* If Model App is it on full size grid or Subgrid?
* Could you provide a screenshot?

**Comment by manishasn161** [comment]
I can see issue happening with standalone PCF control as well.
I can see the grid going blank on scrolling when resolution is 50%. when the resolution is above or below 50% it seems to work fine.
In screenshot I have reduced component container height to 150, so that scroll bar starts appearing.
I have attached two screenshots, 1st one before scrolling and second one after performing scroll.

![image](https://user-images.githubusercontent.com/52907226/95094398-7ca20f00-0747-11eb-9723-e55cef9cc6ce.png)
![image](https://user-images.githubusercontent.com/52907226/95094542-a2c7af00-0747-11eb-861b-2deee4c16fe2.png)

**Comment by rwilson504** [comment]
Thank you for providing the details.  It appears the issue has to do with the sticky footer.  Looking through the MS tickets for Fluent UI I believe the still have some bugs out related to it.  I have gone ahead and moved the footer outside of the details list.  It will now be in a separate div outside of the details list.

I tested this in Chrome and Edge Chromium for Model (grid), Model (subgrid), and Canvas.

![image](https://user-images.githubusercontent.com/7444929/95115418-71cd8700-0713-11eb-8e48-35f16f900ce2.png)

Thanks to @scottdurow for positing this article on PCF DetailList Layout.  Made this a lot faster to fix.
https://community.dynamics.com/crm/b/develop1/posts/pcf-detailslist-layout-with-fluent-ui-and-sticky
