### ISSUE TITLE
Unable to install managed solution due to azure maps authentication optionset missing

### ISSUE THREAD

**Issue by ACECEO** [rwilson504/PCFControls#124]
When installing the latest AzureMapsGridControl_managed.zip solution or any of the previous, I get the following error. Is there a missing component that needs to be bundled into the solution or am I doing something wrong?

<img width="1070" alt="Screen Shot 2020-11-28 at 7 34 27 PM" src="https://user-images.githubusercontent.com/45304395/100529018-e9b6ab80-31b0-11eb-9014-b32d95805fe8.png">

**Comment by Mpr1983** [comment]
I have the same problem!!
