### ISSUE TITLE
First Day of Week stuck on Sunday

### ISSUE THREAD

**Issue by gandalf516** [rwilson504/PCFControls#125]
When using the control within plain canvas app, the First day of week in both month and week views is stuck on Sunday even when set to 2 after PA studio reload:
![image](https://user-images.githubusercontent.com/29257081/100600607-c6e7dc80-3301-11eb-8069-58e300e7bad6.png)

**Comment by rwilson504** [comment]
@gandalf516  Are you still having this issue with the most recent version?  I can't seem to duplicate your issue.

![weekStartDay](https://user-images.githubusercontent.com/7444929/105098820-aa9e2b80-5a78-11eb-825d-d4fcefdfbc90.gif)

**Comment by gandalf516** [comment]
@rwilson504 my problem can be reproduced when you leave the calendar language input parameter empty and set just the calendar week start. Then this parameter is not properly handled, even though it should work regardless of the calendar locale (which is en by default, so no need for the calendar language parameter to be set)
