### ISSUE TITLE
Header not scrolling with body when using resource view and more than 10 ressources

### ISSUE THREAD

**Issue by devkao** [rwilson504/PCFControls#128]
Hey, i have the resourceplanning view in my app and using ~ 14 "Resources".
While the body has a horizontal Scrollbar. the Header does not (as well as the header width is to small) .

From what i have seen the base react version is not having this issue.
can this be fixed?

![grafik](https://user-images.githubusercontent.com/5108510/105020818-14eaa800-5a48-11eb-872d-f5c4e5dd3a39.png)

Thanks alot

**Comment by rwilson504** [comment]
@devkao 

I was able to replicate it, I'll take a look.
