### ISSUE TITLE
Android only allows you to select image files

### ISSUE THREAD

**Issue by Knots23** [rwilson504/PCFControls#137]
Neat little component that allows us to upload a file. It works great in the browser!
On Android devices, we ran into the issue that, no matter the value of the "accepted file types" property, only image files can be selected.

We're tried ".pdf", "pdf", "application/pdf", "file/pdf", "*", but only images can be selected. (Android 9)

Is this a bug in the component?

**Comment by rwilson504** [comment]
Unfortunately it's actually a limitation of the mobile client.  I'm hoping at some point that they open it up to other file types.
