### ISSUE TITLE
Dates not appearing on calendar correctly?

### ISSUE THREAD

**Issue by Mattw112** [rwilson504/PCFControls#189]
I created the fields as you did.  I have a start/end, etc.

The date field I created as Date only type.

For testing I added two records with todays date.

But on the calendar they are showing as yesterday?

Is it because I created the dates as date only?

Terry

**Comment by rwilson504** [comment]
Is this in a model app?  If so it's probably because the calendar uses the current time zone your user settings are set to and using a date field would set the time to the beginning of the day and if you are in something like east time zone it would set it to -5 hours, so the day before.
