### ISSUE TITLE
Adding the Bing Maps Control to a Form

### ISSUE THREAD

**Issue by bpremji** [rwilson504/PCFControls#192]
Hi,

Has anyone tried to add the Bing Maps control to a form (on a subgrid of data).  Whatever I do I cant seem to make the map bigger than what seems to be 4 lines,  I have tried the number of rows in the row layout to 20 and also tried ticking the Automatically expand to use available space tickbox without any luck.  I've attached a screenshot:

![BingMap on Form](https://user-images.githubusercontent.com/45225250/126350963-ccd59b92-4f3a-4e41-be3e-b7d8fc93a1a1.jpg)

Thanks

**Comment by rwilson504** [comment]
Fixed issue where map to does re-size to subgrid in release 1.1.0.70

**Comment by joannachongshen** [comment]
Hi @rwilson504 , I might have the same issue here. The subgrid rows set to 25 and "Use available space" enabled. The map does not resize. Am I missing a config? Thanks. 
![image](https://github.com/rwilson504/PCFControls/assets/115131497/6af25af0-01ba-4690-9350-daec142edde1)
![image](https://github.com/rwilson504/PCFControls/assets/115131497/42ac12db-d01e-4775-88a4-7aaf0e69399d)
