### ISSUE TITLE
Adding any collection to calendar causes canvas stuido to crash instantly 

### ISSUE THREAD

**Issue by anongen01** [rwilson504/PCFControls#193]
Timeline of issue:

1. Import component following Microsoft's documentation.
2. Created a new blank canvas app.
3. Added component to app.
4. Saved and reopened. Component visible.
5. Added collection to on visible property, using the fields specified in documentation, with the correct data types.
6. Added collection as data source for calendar, both by selecting it from the drop-down or hard coding it directly into the items field.
7. App crashes. *sad face*

Ive tried every other way of getting this to work, and I'm disappointed because it looks awesome. Thanks for putting so much work into this by the way! It looks amazing, I just need to get it working on my end.

**Comment by rwilson504** [comment]
@anongen01 I just gave this a try and you are correct there appears to be loop when retrieving the data causing the page to crash.  The PCF component functionality for canvas recently got moved from Preview to General Availability by MS so I'll take a look at what updates were done and get the component fixed.  Thanks for letting me know!

**Comment by rwilson504** [comment]
@anongen01 I just did a new release which should fix the issue.

https://github.com/rwilson504/PCFControls/releases/tag/1.1.0.65

Just one note, after you set the field names in the properties do a save and publish, then close the canvas studio and come back in to see those changes.  At some point I'll add some support for changing those field names on the fly but I wanted to get this larger bug fixed first.

Thanks,

Rick
