### ISSUE TITLE
Using Color Slider Does Not Update Palette

### ISSUE THREAD

**Issue by rwilson504** [rwilson504/PCFControls#2]
The color palette does not update when using the slider on the initial open of the color picker if the color is set to #ffffff.

Issue found by @MitchMilam

**Comment by rwilson504** [comment]
This was a bug which was fixed by the Office Fabric UI team.  I will update the Color Picker to utilize the newer version of the libraries.

**Comment by MitchMilam** [comment]
Cool. Thanks!
