### ISSUE TITLE
Event color not responding

### ISSUE THREAD

**Issue by wendellsimmons** [rwilson504/PCFControls#213]
HI Rick, the Calendar is working great except for one thing: Event Color Field does not respond to any Hex codes or fields with Hex codes. In this test all of the events display the Default Event Color even though there is a hardcoded Event color that I understand should overwrite the default.

![image](https://user-images.githubusercontent.com/73668530/142649981-e76ab4d0-d682-4039-9abe-0518e44afb34.png)

**Comment by rwilson504** [comment]
@wendellsimmons Hard coding the Event Color property will not work.  Instead what that property is asking for is the column which holds the hex values.  Basically the hex color needs to be included in your data set.  For example if you had a collection like this where the hex value was being stored in the ResourceColor field then the **Event Color Field** property would be set to **ResourceColor**.

```
ClearCollect(
    finalEvents,
    AddColumns(
        Events,      
        "EventStart",
        Start,
        "EventEnd",
        End,
        "EventName",                
        Name,
        "EventColor",
        Color**
        "EventId",
        Events
    )
);
```

Thing of a record in this collection looking something like this
{
"EventStart" : "2020-01-01",
"EventEnd" : "2020-01-01",
"EventName" : "My Event",
**"EventColor" : "#eeefff",**
"EventId" : "2c23932f-7d2e-4016-9ea4-791537cbe073"
}

**Comment by wendellsimmons** [comment]
Hi Rick,
Originally I used a text color field added to the Appointments table,
populated with hexcodes as below.

[image: image.png]


Here is the Appointment data...
[image: image.png]

And the results are always the default color...
[image: image.png]


Wendell Simmons | kcvisual.media | +1.510.919.0517
