### ISSUE TITLE
Open record button in Bing maps pcf does not work from custom page or canvas app

### ISSUE THREAD

**Issue by Arwa91** [rwilson504/PCFControls#216]

**Comment by rwilson504** [comment]
Create a new output property called selectedRecordId.  When the component is used in a Canvas app with a Dataverse dataset this property will be set when the user clicks on Open Record in the popup box of a record.  The developer can then use this value to create Canvas functionality for viewing the record.  Additionally added another property called idFieldName to the component, this will allow you to select a specific field you would like to set as the id field for records if you are passing in the data as a collection to the component.

Closed in release 1.1.0.70
