### ISSUE TITLE
Scroll Bar Broken

### ISSUE THREAD

**Issue by evanh1393** [rwilson504/PCFControls#219]
Hey,

I've been attempting to get the control working, but the scroll bar seems to always snap to a specific time. Is there a way to have it not do that? Or is this because of another issue I may not be aware of.

Thanks

**Comment by Jakez1234** [comment]
> Hey,
> 
> I've been attempting to get the control working, but the scroll bar seems to always snap to a specific time. Is there a way to have it not do that? Or is this because of another issue I may not be aware of.
> 
> Thanks

I have the same problem but it only started recently, meaning I had it working when first installed until recently. To my knowledge I didn't change anything. Did you ever find a solution? 

Thanks

**Comment by rwilson504** [comment]
There is a property called Calendar Scroll To Time, you can set that between 0-23 to determine where it will scroll to, set it to 0 if you don't want it to scroll.
