### ISSUE TITLE
Subgrid

### ISSUE THREAD

**Issue by popujol** [rwilson504/PCFControls#231]

**Comment by popujol** [comment]
Hello 
I am facing issue when displaying the control in a subgrid, it is very small and cant be read.

The use case is : An Account has a Parent account, from the parent account we would like to see the childs

Is it normal? Thank you!

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/40460576/161714588-fc65154b-17ab-4867-b5da-586be683819e.png)

Pierre-Olivier

**Comment by rwilson504** [comment]
Open your form in the maker portal and click on the subgrid.  Then adjust the following property to find the size you would like.

Maximum number of rows:  Typically, this determines the maximum number of records to display in the subgrid but in the case of the PCF it will make the height of the control to (Maximum number of rows * 1.5)em.
