### ISSUE TITLE
Calendar Read-Only Views?

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#27]
Can the calendar be configured to just show scheduled items as read-only?  In my case, scheduling of new or editing of existing items would happen via custom UI in a canvas app outside of the calendar control.

Also, is the color for each record passed in as HEX?

Great job on creating this!
Thanks

**Comment by rwilson504** [comment]
When the calendar is on a Canvas app it really is read-only anyway unless the developer does something.  The control just provides output parameters that contain information such as the id of the item you clicked on or the time span that you selected.  It's up to you as the dev to decide what you want to do with that information.

Also the colors should be in hex format, #000000.  I also have a PCF color picker you can utilize to help with that. [PCF Color Picker](https://pcf.gallery/pcf-color-picker/)

**Comment by ArtKarp** [comment]
On the example gif:  The line where you pick a color it shows the HEX number next to it.  Can the HEX on that line be hidden?  or bound to a field?   What I would want to do is show the color and the HEX one time.   Or, if someone typed/pasted in a HEX code, the color would change to the new color.  This way the user could use the color picker to show a color and get the HEX code or type in a HEX code and see the color.

**Comment by rwilson504** [comment]
So the picker control is actually bound to whatever text field you add the control to, so any updates will be reflected in that field.  As far as being able to type in the hex color you can do so by clicking on the color button and opening the color picker interface.  The color picker iteself allows you to update the hex.  I did it this way because the picker handled validation of the hex values.

![image](https://user-images.githubusercontent.com/7444929/80612289-c56fd200-8a09-11ea-933d-9987b04f8f29.png)

**Comment by ArtKarp** [comment]
Ok that works.  Very nice!

Does the picker have an option to support the alpha channel (RGBA) and HEX (8 char) that includes alpha bits?

**Comment by rwilson504** [comment]
That could be added to the PCF control, I would probably make it a property on the control on whether or not to show that.  The Office Fabric UI component i build this off of does offer that.

**Comment by ArtKarp** [comment]
It would be great to have.   In a canvas app, when you set a color property the design control shows HEX and RGBA inputs. So that would just make it match.

**Comment by rwilson504** [comment]
So just dug into the ColorPicker i'm using.  It's actually the same one MS uses.  It does not currently support 8 digit hex values but i put in a feature request for it in github, if they update the control i'll add it in.
