### ISSUE TITLE
Calendar localization?

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#28]
Does the calendar have the ability to be localized for language (E.G. Pass in "DE" and have the calendar control text like "month names", "day of week", "Today" be displayed in German)?

**Comment by rwilson504** [comment]
It appears that react-big-calendar does support languages through the use of it's props.

Would you mind providing German translation for the items below?

``
let defaultMessages = {
  date: 'Date',
  time: 'Time',
  event: 'Event',
  allDay: 'All Day',
  week: 'Week',
  work_week: 'Work Week',
  day: 'Day',
  month: 'Month',
  previous: 'Back',
  next: 'Next',
  yesterday: 'Yesterday',
  tomorrow: 'Tomorrow',
  today: 'Today',
  agenda: 'Agenda',

  noEventsInRange: 'There are no events in this range.',

  showMore: total => `+${total} more`,
}
``

Thanks,

Rick

**Comment by rwilson504** [comment]
Hey can you tell me if you are looking for localization right now on Model or Canvas?  I ask because doing this on Model is not too bad and you can utilize the Users Settings to do it.  Unfortunately because Canvas app code components are still preview you can't get the users language settings in Canvas, which makes it more difficult.  Not that it wouldn't be possible in Canvas but I would just need to take another approach.

Thanks,

Rick

**Comment by ArtKarp** [comment]
I am looking to use this in a canvas app.

One way to do this would be just to pass in JSON to the control that is already populated with the paired values language text needed.   This would also all you to pass in custom text.  For example, changing "There are no events in this range" to "There are no scheduled items in the selected date range".  If nothing is passed, you could default to English.   This would be easy to set up for the top 5 Dynamics languages so a dev could just copy paste it into their canvas app.  And easy for them to customize for other languages.   If the control already had languages built in, it would be easier to just pass in a two  or four char culture.   I say pass in in because by default you don't know which language a user wants to use in the app.  In CDS the user has a default setting for which language they want to use (this may or may not be their current browser culture/language). So CDS setting  could read and passed in.  However, in testing the dev may need another language, because they don't speak Spanish and their browser is set to en-us, for example. 

JSON Input Examples:

Spanish
---------------------
{
date: 'Fecha',
time: 'Hora',
event: 'Evento',
allDay: 'Todo el dia',
week: 'Semana',
work_week: 'Semana de trabajo',
day: 'Día',
month: 'Mes',
previous: 'atrás',
next: 'Siguiente',
yesterday: 'Ayer',
tomorrow: 'Mañana',
today: 'Hoy',
agenda: 'Calendario',
noEventsInRange: 'No hay elementos programados en el intervalo de fechas.'
}

English
---------------------------------
{
date: 'Date',
time: 'Time',
event: 'Event',
allDay: 'All Day',
week: 'Week',
work_week: 'Work Week',
day: 'Day',
month: 'Month',
previous: 'Back',
next: 'Next',
yesterday: 'Yesterday',
tomorrow: 'Tomorrow',
today: 'Today',
agenda: 'Agenda',
noEventsInRange: 'There are no items scheduled in the selected date range.'
}

**Comment by rwilson504** [comment]
I do love the JSON idea and i think in the future that will work.  Unfortunately right now there is a bug that does not allow more than 100 characters in an input field in Model apps, even if that field is a MultiLine text.  I also looked into just using the RESX files but unfortunately those are not working in Canvas app right now.  For the time being I'm going to hard code languages and allow you to enter a parameters to configure the one you want for Canvas.  If you are in a model app I'm goign to use the language you have set in your users settings unless a parameter values has been specifically added into the control.  I worked on de, fr and now thanks to you i also have es.  Thanks and I'll have an update out soon.

**Comment by ArtKarp** [comment]
A few thoughts:

I would let the language be passed in as an input.  This lets the app dev get and save the culture as a global var one time in a canvas app and then reuse it.  It also avoids having to query the org about the user language every time the calendar is opened.  Since model app forms have/can pass "context" I am not sure the same applies in that case.

Since there is a limitation/bug on 100 chars, with a canvas app could a dev just pass in the name of a collection that contains the language settings for a canvas app?  This would allow a dev to create a collection(s) with one or more languages.  Since this is a control for both canvas and model, I don't know if this is a great idea but thought I would put it out there.

Since model app views now allow a calendar view out of the box when enabled.  Have you created a  feature comparison?  In the context of model apps, I am trying to figure out reasons why I would choose the CDS view control calendar vs the React one.

Thanks

**Comment by rwilson504** [comment]
Thanks for the ideas. I'm definitely going to allow the user to pass it in as a parameter. 

Also as far as the feature differences between mine and the MS one I would say it's the ability to see events by Resource, that is definitely not something you can do with the build in one.


Thanks again.

--Rick
