### ISSUE TITLE
Italian translation for Calendar Control

### ISSUE THREAD

**Issue by GuidoPreite** [rwilson504/PCFControls#31]
case 'it':
                return {
                    date: 'Data',
                    time: 'Ora',
                    event: 'Evento',
                    allDay: 'Tutto il giorno',
                    week: 'Settimana',
                    work_week: 'Settimana lavorativa',
                    day: 'Giorno',
                    month: 'Mese',
                    previous: 'Indietro',
                    next: 'Avanti',
                    yesterday: 'Ieri',
                    tomorrow: 'Domani',
                    today: 'Oggi',
                    agenda: 'Calendario',              
                    noEventsInRange: 'Non ci sono eventi in queste date.',              
                    showMore: total => `+${total} altri`
                }

**Comment by rwilson504** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/7444929/80713356-4fc73d00-8ac1-11ea-94e6-0144b7275d6f.png)
