### ISSUE TITLE
[BUG] [Bing Maps Grid] Open Record link doesn't work

### ISSUE THREAD

**Issue by MandarbZA** [rwilson504/PCFControls#312]
**Which PCF Component**
Bing Maps Grid

**What type of Power App are you using this PCF component in?**
 - Model App

**Describe the bug**
The Open Record link displayed on a pin doesn't do anything. I debugged the JavaScript as much as my knowledge allows, and clicking on the link defintely gets the table name and record ID, but it doesn't navigate away

**To Reproduce**
1. Configure view with Bing Maps
2. Hover over a pin, and click on the Open Record link
3. Nothing happens

**Expected behavior**
Either redirect to or open in a new tab the related record

**Screenshots**
Configuration
![image](https://user-images.githubusercontent.com/15384759/223412356-e050fb51-1f0f-4da2-98d6-0a1ca9c1d379.png)
![image](https://user-images.githubusercontent.com/15384759/223412423-c2d8c1f0-1397-441a-9b2c-2600300a0b55.png)
![image](https://user-images.githubusercontent.com/15384759/223412628-f07c0542-723c-4f47-b91c-6d17fd3132a7.png)
In map view:
![image](https://user-images.githubusercontent.com/15384759/223412723-e1d806cd-7b96-424c-9d85-75fb2ff6c1af.png)
![image](https://user-images.githubusercontent.com/15384759/223412770-ee688b5c-8b20-4fe6-8421-7c47a8faa6b6.png)

**Additional context**

**Comment by MandarbZA** [comment]
I enabled the control on tables that have the above table in the screenshots as a lookup, and it works as expected there. The only real difference I can see is that the table has a hierarchy enabled.

**Comment by rwilson504** [comment]
Can you check to see if you have the primary name field for the table included in the view?

![image](https://user-images.githubusercontent.com/7444929/223552136-0d5d2ebf-ece7-4521-84b9-f06ee4f7f696.png)

**Comment by MandarbZA** [comment]
Hi
It was definitely not working when I posted this yesterday, and I worked on importing more data after that. This morning it's working. Sorry about that. This is the view, and definitely had the name.
![image](https://user-images.githubusercontent.com/15384759/223627350-8003a530-c37b-46a9-abfd-42239382daa5.png)
