### ISSUE TITLE
[FEATURE] link any entity to the calander, instead of event 

### ISSUE THREAD

**Issue by shultami** [rwilson504/PCFControls#318]
Hi,
Is it possible to link the calander to any custom or vanila entity, like task of custom event?

**Comment by okn-x** [comment]
Any progress with this one?

Is this reflected in the documentation that the entities and thus this solution is name-specific ?

**Comment by rwilson504** [comment]
There is no requirements to create a table called Events.  The control is accessible for any table within your system including custom tables.  In a model app you just need to add the control to whatever view on whatever table you like.  In canvas apps you can build your own collection with data coming from anywhere.
