### ISSUE TITLE
[FEATURE] [Calendar] Adjustable steps and timeslots

### ISSUE THREAD

**Issue by Craig-Humphrey** [rwilson504/PCFControls#319]
**Which PCF Component**
Calendar

**Is your feature request related to a problem? Please describe.**
I have a client that's wanting to adjust the "bucket" (timeslots), from the default 30 minutes to 15 minutes and potentially 5 or 10 minutes - we need to experiment to see what works best for the users.

**Describe the solution you'd like**
This guy: https://www.youtube.com/watch?v=Opjbv-TOb14&t=1307s appears to have implemented adjustable steps and timeslots, against the original react-big-calendar, though he doesn't appear to have released the solution.

So, I'm looking for the same idea, where you can adjust the number of timeslots per hour and the length (in minutes) of the timeslots.
I'm not entirely sure why he has the two disconnected, possibly so he can have things like 90 minute timeslots, but then I'm not sure what he'd use for steps (number of timeslots per hour).

My focus is on being able to have more timeslots per hour, in particular, so that users can see the gaps between appointments - the current 30 minute timeslots don't visualize <30 minute gaps between appointments.  e.g. two appointments on the same day: 900-915 and 930-945, will not show a gap.

**Describe alternatives you've considered**
I started looking at your code and comparing it with the code from the YouTube above and looked at the original react-big-calendar, but there's quite a few structural differences, plus I have zero knowledge of REACT and minimal PCF...  So I'm hoping this isn't a big deal.

**Additional context**
Happy to help out in anyway I can!

**Comment by Nelle999** [comment]
Second this 👍
