### ISSUE TITLE
[BUG] [Calendar Control] Event Color Issue

### ISSUE THREAD

**Issue by JannyM85** [rwilson504/PCFControls#322]
I use Calendar Control, the latest version in Model Driven App. I have an entity in_vacation, where there is an in_eventcolor field. I am trying to set this field to the Event Color property, but the calendar still shows Default Color.  All data in entity have fill this attribute with different color than the default color. 

![image](https://github.com/rwilson504/PCFControls/assets/13817757/14b1559d-90d9-425d-bed9-c680367408fa)
![image](https://github.com/rwilson504/PCFControls/assets/13817757/5d349898-0a15-4434-ac19-bb2fe7fdb91a)

Can help me with correct setup? Thanks.

**Comment by rwilson504** [comment]
@JannyM85  , what is the format of the data you have in the in_eventcolor column?  The data should be hex colors.

**Comment by JannyM85** [comment]
Hello, offcourse the format is hex.

**Comment by rwilson504** [comment]
@JannyM85, Just to confirm can you send a screenshot of one of the records showing data in the in_eventcolor field.

**Comment by rwilson504** [comment]
@JannyM85, Also is the in_eventcolor field included in the View when you configured it.  All data field that are being used must be in the View.

**Comment by JannyM85** [comment]
Hello, thank you for the information. Adding the field to the view helped.   If I may I would like to offer my view, in case the component is not configured correctly it should report an error. Your implementation pretends that everything is working, however the field was not in the data. Please consider modifying the validation of the configuration data so that if the component is misconfigured it returns the appropriate error.
