### ISSUE TITLE
Scroll To Hour on Day View

### ISSUE THREAD

**Issue by rwilson504** [rwilson504/PCFControls#39]
Allow the calendar to automatically scroll to a specific hour on the day view calendar.

-Add a new parameters so user can enter hour from 0-24.
-When user clicks on day view scroll the calendar automatically to that hour of the day.

**Comment by ArtKarp** [comment]
Don't go overboard.   0-23 should cover everyone.  :)

Thinking out loud:  
Although you might just need 0-18 or so?....
If someone did specify hour "20"  and there were only a few items for the day, would it just position 23:00 at the bottom and build the view from there up?  With only a few items scheduled during daylight hours you are easily able to see from 12 PM to Midnight and have very little scroll bar distance.
