### ISSUE TITLE
View Column Header Alignment

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#40]
On the calendar week view, the date column headers are misaligned with the hour columns below them.  The  Sunday column header is 30 px to the right of the hours column below.  The day and agenda views headers are a bit off too.

**Comment by rwilson504** [comment]
I'm going to fix this by setting these columns to a fixed amount.  Right now the control calculates it but due to the nature of how the control is loaded in the Canvas Player it's throwing off those calculations.
