### ISSUE TITLE
Ability to specifiy scheduled item text color

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#41]
Currently there is the ability to specify a color which is used as a background color for each scheduled item.  It would be great if we could specify the color of the text to be used on the background for each item.  Currently the default text is black for all scheduled items.  Using black eliminates the ability to use darker colors. (e.g. brown, dark blue, deep purple) as a background.

**Comment by rwilson504** [comment]
I don't currently have a property you can set for the text color instead what is currently implemented is that if you choose a darker color the text will transform from black to white.

![image](https://user-images.githubusercontent.com/7444929/81477308-1ab79a80-91e5-11ea-9ae4-123b1aea833f.png)

**Comment by ArtKarp** [comment]
Oooh.  That's like magic.   I see it in my testing. Thanks!
