### ISSUE TITLE
Resource Scrolling in Week Views

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#57]
The all day events scroll into the time column, which I don't think is by design. 

![image](https://user-images.githubusercontent.com/25698082/82382371-ad73e880-99e0-11ea-99fd-7ebc216d4beb.png)

**Comment by ArtKarp** [comment]
Another image with multiple all day events.

![image](https://user-images.githubusercontent.com/25698082/82391656-b079d380-99f6-11ea-8e57-21dd402ffceb.png)

**Comment by rwilson504** [comment]
This is happening because i made the time bar transparent.

**Comment by rwilson504** [comment]
There is not really a way to fix this unless we put a background color on the timebar.  Any other fix would require a large re-write of the react-big-calendar control which would be too much of a change.    
I'm starting to think it may be a good idea to add a parameter to just set an overall background color for the calendar which would also set the time bar to that color.
