### ISSUE TITLE
Month View More Links

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#58]
I scheduled seven items per day for four days (May 18-21).  In the month view when you click on the links for each of the four days they all open the day view to May 21.  The current calendarDate is set to 5/21. 

![image](https://user-images.githubusercontent.com/25698082/82391547-6abd0b00-99f6-11ea-8d79-5ed85ced6e6b.png)

BTW: The new more links look great!

**Comment by rwilson504** [comment]
I could not duplicate this but it could be happening from the other issue i just fixed where the calendar held onto the datetime. #56.  Re-check this after i get the next release posted.

Thanks,

Rick

**Comment by ArtKarp** [comment]
I tested this with the update and now it works as expected.
