### ISSUE TITLE
"Today" Background color is being applied to all months

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#59]
I changed the default Today color and see that it is being applied for the same day number for all months.  (e.g. If today is May 19 the color shows on the 19th of every month).  This is true in the Month, Week, Work, Week, and Day calendar views.  If I remove my custom color, the default blue shows up the same way.

**Comment by rwilson504** [comment]
I see the issue I just looked at the Date portion which is the day of the month.
