### ISSUE TITLE
Adding Work Week Causes International Button Spacing Trainwreck at End of Year

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#68]
Oops...

![image](https://user-images.githubusercontent.com/25698082/82856314-81fe6b80-9ec2-11ea-981f-5946c4d66682.png)

**Comment by rwilson504** [comment]
Here is what I'm going to do for this one.
-Shrink the time label to 14px.
-Reduce the amount of padding on the buttons.
-Set the toolbar to not wrap.
-Set the text of the label to not show any overflow.

![image](https://user-images.githubusercontent.com/7444929/83910172-12954100-a738-11ea-9c2e-db2efe1cc25b.png)

Also I'm adding in a new property called calendarAvailableViews.  Here you can select which view the calendar can have.  It's a comma delimited string that can contain the following values month, week, work_week, day, agenda.  Using this you can select which view buttons will show up.  If you only include a single view then no buttons even show up.  This could be useful if you always want the users to look at a month view or maybe you don't care about the Agenda view and want to leave it out.  Also you can array the view names in this string and the buttons will show up in that order.  So if you want the work_week view and the end just put it at the end of the property string.

  
![image](https://user-images.githubusercontent.com/7444929/83910437-88011180-a738-11ea-9d6d-bf5fb3b4b9e8.png)
