### ISSUE TITLE
How do I download the zip file?

### ISSUE THREAD

**Issue by roryneary** [rwilson504/PCFControls#90]
Apologies for my ignorance, but I was looking for a zip file that I can then import in as a solution, but I can't work out how to get it.  How do we do this?

**Comment by rwilson504** [comment]
Hey Rory,

The solution files are available via the releases tab in github.   Additionally i have created download links on the main REAMDE.md file for each control.  Hope this helps.

Rick

![Releases Tab](https://user-images.githubusercontent.com/7444929/85408715-e00a8700-b532-11ea-87f1-dfddd9353f86.png)

![Assets](https://user-images.githubusercontent.com/7444929/85408660-cd904d80-b532-11ea-9d30-f891610ed958.png)

![Main README File](https://user-images.githubusercontent.com/7444929/85408621-c1a48b80-b532-11ea-8e24-4ce67a6be165.png)

**Comment by roryneary** [comment]
Brilliant - thanks.
